# Generated by Django 3.1.12 on 2021-06-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20210624_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
