# Generated by Django 3.1.12 on 2021-07-02 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20210701_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='year',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 4, 29, 14, 725991, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 4, 29, 14, 725966, tzinfo=utc)),
        ),
    ]
