# Generated by Django 3.1.12 on 2021-07-02 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_auto_20210701_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 4, 29, 14, 726630)),
        ),
    ]
