# Generated by Django 3.1.12 on 2021-07-02 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_auto_20210702_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 4, 32, 31, 559452)),
        ),
    ]
